export const EthLotteryAbi = [
  {
    type: 'error',
    name: 'ERC20InsufficientAllowance',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'allowance', type: 'uint256' },
      { name: 'needed', type: 'uint256' },
    ],
  },
  {
    type: 'constructor',
    inputs: [
      { name: '_Withdraw', type: 'address', internalType: 'contract IWithdraw' },
      { name: '_Cancel', type: 'address', internalType: 'contract ICancel' },
      { name: '_Update1', type: 'address', internalType: 'contract IUpdate1' },
      { name: '_Update3', type: 'address', internalType: 'contract IUpdate3' },
      { name: '_Update5', type: 'address', internalType: 'contract IUpdate5' },
      { name: '_Update11', type: 'address', internalType: 'contract IUpdate11' },
      { name: '_Update21', type: 'address', internalType: 'contract IUpdate21' },
      { name: '_Update44', type: 'address', internalType: 'contract IUpdate44' },
      { name: '_Update89', type: 'address', internalType: 'contract IUpdate89' },
      { name: '_Update179', type: 'address', internalType: 'contract IUpdate179' },
      { name: '_Token', type: 'address', internalType: 'contract IERC20' },
      { name: '_Router', type: 'address', internalType: 'contract IUniswapV2Router02' },
      { name: '_BetMin', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'fallback', stateMutability: 'payable' },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'D',
    inputs: [],
    outputs: [
      { name: 'periodStartBlock', type: 'uint64', internalType: 'uint64' },
      { name: 'commitBlock', type: 'uint64', internalType: 'uint64' },
      { name: 'nextIndex', type: 'uint32', internalType: 'uint32' },
      { name: 'dividendPeriod', type: 'uint16', internalType: 'uint16' },
      { name: 'betsLimit', type: 'uint8', internalType: 'uint8' },
      { name: 'betsStart', type: 'uint8', internalType: 'uint8' },
      { name: 'betsIndex', type: 'uint8', internalType: 'uint8' },
      { name: 'commitIndex', type: 'uint8', internalType: 'uint8' },
      { name: 'status', type: 'uint8', internalType: 'uint8' },
    ],
    stateMutability: 'view',
  },
  { type: 'function', name: 'adminwithdraw', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'betMin',
    inputs: [],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betPower1',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betPower2',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betPower3',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betSum',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bets',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betsIndex',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betsLimit',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'betsMax',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancel',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract ICancel' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancelbet',
    inputs: [
      { name: '_pA', type: 'uint256[2]', internalType: 'uint256[2]' },
      { name: '_pB', type: 'uint256[2][2]', internalType: 'uint256[2][2]' },
      { name: '_pC', type: 'uint256[2]', internalType: 'uint256[2]' },
      { name: '_betIndex', type: 'uint256', internalType: 'uint256' },
      { name: '_recipient', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'changeGenerator',
    inputs: [{ name: '_who', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'changeOwner',
    inputs: [{ name: '_who', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  { type: 'function', name: 'close', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'collect',
    inputs: [
      { name: '_pA', type: 'uint256[2]', internalType: 'uint256[2]' },
      { name: '_pB', type: 'uint256[2][2]', internalType: 'uint256[2][2]' },
      { name: '_pC', type: 'uint256[2]', internalType: 'uint256[2]' },
      { name: '_root', type: 'uint256', internalType: 'uint256' },
      { name: '_nullifierHash', type: 'uint256', internalType: 'uint256' },
      { name: '_recipient', type: 'address', internalType: 'address' },
      { name: '_relayer', type: 'address', internalType: 'address' },
      { name: '_fee', type: 'uint256', internalType: 'uint256' },
      { name: '_refund', type: 'uint256', internalType: 'uint256' },
      { name: '_rewardbits', type: 'uint256', internalType: 'uint256' },
      { name: '_invest', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'collectDividend',
    inputs: [{ name: '_who', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'commit',
    inputs: [
      { name: '_commitHash', type: 'uint256', internalType: 'uint256' },
      { name: '_maxUpdate', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'commitBlockHash',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'commitHash',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'commitIndex',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currentBalance',
    inputs: [],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dividendFeePerCent',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dividendPeriod',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'generator',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'generatorFeePerCent',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lastRoot',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxUpdate',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextIndex',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nullifier',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payOut',
    inputs: [{ name: '_amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'periodBets',
    inputs: [{ name: 'period', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'periodBlocks',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'periodShares',
    inputs: [{ name: 'period', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'periods',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'bets', type: 'uint128', internalType: 'uint128' },
      { name: 'shares', type: 'uint128', internalType: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'play',
    inputs: [
      { name: '_secrethash', type: 'uint256', internalType: 'uint256' },
      { name: '_power', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'playAndPray',
    inputs: [
      { name: '_secrethash', type: 'uint256', internalType: 'uint256' },
      { name: '_power', type: 'uint256', internalType: 'uint256' },
      { name: '_prayer', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'playETH',
    inputs: [
      { name: '_secrethash', type: 'uint256', internalType: 'uint256' },
      { name: '_power', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'playETHAndPray',
    inputs: [
      { name: '_secrethash', type: 'uint256', internalType: 'uint256' },
      { name: '_power', type: 'uint256', internalType: 'uint256' },
      { name: '_prayer', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'pray',
    inputs: [
      { name: '_betId', type: 'uint256', internalType: 'uint256' },
      { name: '_prayer', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'prayer',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'rememberHash', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'reopen', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'resetcommit', inputs: [], outputs: [], stateMutability: 'payable' },
  {
    type: 'function',
    name: 'reveal',
    inputs: [
      { name: '_revealSecret', type: 'uint256', internalType: 'uint256' },
      { name: '_pA', type: 'uint256[2]', internalType: 'uint256[2]' },
      { name: '_pB', type: 'uint256[2][2]', internalType: 'uint256[2][2]' },
      { name: '_pC', type: 'uint256[2]', internalType: 'uint256[2]' },
      { name: '_newRoot', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'roots',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'router',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUniswapV2Router02' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'secret',
    inputs: [{ name: '_revealSecret', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'token',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update1',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate1' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update11',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate11' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update179',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate179' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update21',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate21' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update3',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate3' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update44',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate44' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update5',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate5' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'update89',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUpdate89' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'updateDividendPeriod', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'walletBalanceOf',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'walletDividendPeriodOf',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'walletSharesOf',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'walletWithdrawPeriodOf',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IWithdraw' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'LogBetIn',
    inputs: [
      { name: 'index', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newHash', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogCancel',
    inputs: [{ name: 'index', type: 'uint256', indexed: true, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogChangeGenerator',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newGenerator', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogChangeOwner',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogClose',
    inputs: [{ name: 'owner', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogCommit',
    inputs: [
      { name: 'index', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'commitIndex', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'commitHash', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogHash',
    inputs: [{ name: 'commitBlockHash', type: 'uint256', indexed: true, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogPrayer',
    inputs: [
      { name: 'betId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'prayer', type: 'bytes32[]', indexed: false, internalType: 'bytes32[]' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogReopen',
    inputs: [{ name: 'owner', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogResetCommit',
    inputs: [{ name: 'owner', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogSecret',
    inputs: [
      { name: 'lastRoot', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'revealSecret', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogUpdate',
    inputs: [
      { name: 'index', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newRand', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newRoot', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogWin',
    inputs: [
      { name: 'nullifierHash', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'reward', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LogWithdraw',
    inputs: [{ name: 'owner', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
]
